/** Shared motion curves for route / auth transitions. */
export const MOTION_EASE_OUT = [0.22, 1, 0.36, 1] as const;
export const MOTION_EASE_IN_OUT = [0.45, 0, 0.2, 1] as const;

export const ROUTE_SWEEP_MS = 560;
export const AUTH_SWEEP_MS = 420;
export const DISPLAY_PIN_REVEAL_MS = 480;
export const DISPLAY_PIN_REVEAL_REDUCED_MS = 120;
export const DISPLAY_PIN_REJECT_MS = 420;
export const DISPLAY_PIN_REJECT_REDUCED_MS = 140;
export const DISPLAY_CELEBRATION_HOLD_MS = 720;
export const DISPLAY_CELEBRATION_ENTER_MS = 620;
export const DISPLAY_CELEBRATION_EXIT_MS = 620;
export const DISPLAY_CELEBRATION_HOLD_REDUCED_MS = 100;
export const DISPLAY_CELEBRATION_ENTER_REDUCED_MS = 140;
export const DISPLAY_CELEBRATION_EXIT_REDUCED_MS = 140;
/** @deprecated Alias — bitte DISPLAY_CELEBRATION_* nutzen */
export const DISPLAY_TIME_CELEBRATION_HOLD_MS = DISPLAY_CELEBRATION_HOLD_MS;
export const DISPLAY_TIME_CELEBRATION_EXIT_MS = DISPLAY_CELEBRATION_EXIT_MS;
export const DISPLAY_TIME_CELEBRATION_HOLD_REDUCED_MS = DISPLAY_CELEBRATION_HOLD_REDUCED_MS;
export const DISPLAY_TIME_CELEBRATION_EXIT_REDUCED_MS = DISPLAY_CELEBRATION_EXIT_REDUCED_MS;
export const MARKETING_SWEEP_MS = 520;

export const ROUTE_SWEEP_REDUCED_MS = 120;
