# Production-Image für Coolify / VPS (git-SHA als Tag, kein festes live-proxy).
FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SITE_URL=https://new.gwada.app
ARG NEXT_PUBLIC_SUPABASE_URL=https://new.gwada.app/sb
ARG NEXT_PUBLIC_SUPABASE_PROXY=true
ARG NEXT_PUBLIC_GWADA_SUPABASE_ONLY=false
ARG NEXT_PUBLIC_GWADA_WORKSPACE_SLUG=gwada-demo
ARG SUPABASE_UPSTREAM_URL=http://127.0.0.1:8001
ARG GWADA_BUILD_SHA=unknown

ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PROXY=$NEXT_PUBLIC_SUPABASE_PROXY
ENV NEXT_PUBLIC_GWADA_SUPABASE_ONLY=$NEXT_PUBLIC_GWADA_SUPABASE_ONLY
ENV NEXT_PUBLIC_GWADA_WORKSPACE_SLUG=$NEXT_PUBLIC_GWADA_WORKSPACE_SLUG
ENV SUPABASE_UPSTREAM_URL=$SUPABASE_UPSTREAM_URL
ENV GWADA_BUILD_SHA=$GWADA_BUILD_SHA

RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

ARG GWADA_BUILD_SHA=unknown
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SITE_URL=https://new.gwada.app
ARG NEXT_PUBLIC_SUPABASE_URL=https://new.gwada.app/sb
ARG NEXT_PUBLIC_SUPABASE_PROXY=true
ARG NEXT_PUBLIC_GWADA_SUPABASE_ONLY=false
ARG NEXT_PUBLIC_GWADA_WORKSPACE_SLUG=gwada-demo
ARG SUPABASE_UPSTREAM_URL=http://127.0.0.1:8001

ENV GWADA_BUILD_SHA=$GWADA_BUILD_SHA
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_PROXY=$NEXT_PUBLIC_SUPABASE_PROXY
ENV NEXT_PUBLIC_GWADA_SUPABASE_ONLY=$NEXT_PUBLIC_GWADA_SUPABASE_ONLY
ENV NEXT_PUBLIC_GWADA_WORKSPACE_SLUG=$NEXT_PUBLIC_GWADA_WORKSPACE_SLUG
ENV SUPABASE_UPSTREAM_URL=$SUPABASE_UPSTREAM_URL

COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/public ./public
COPY --from=build /app/content ./content

EXPOSE 3000
CMD ["npm", "start"]
