import { normalizeAppLocale, type AppLocale } from "@/i18n/config";
import type { NotificationModuleId } from "@/lib/notifications/notification-modules";

export type ModuleNoticeLabel = { one: string; many: string };

type Phrase = {
  newMessage: string;
  channel: string;
  received: string;
  followUpDue: string;
  later: string;
  chat: string;
  reason: string;
  due: string;
  guest: string;
  messageFallback: string;
  newReview: string;
  from: string;
  rating: string;
  reviewedOn: string;
  newPendingReservation: string;
  newReservation: string;
  changeRequest: string;
  changeRequestShort: string;
  cancellation: string;
  cancellationShort: string;
  eventInquiry: string;
  eventInquiryShort: string;
  company: string;
  shiftStart: string;
  shiftEnd: string;
  staff: string;
  shift: string;
  time: string;
  start: string;
  planned: string;
  end: string;
  lowStock: string;
  ingredient: string;
  ingredientFallback: string;
  stock: string;
  threshold: string;
  supplier: string;
  supplierFallback: string;
  overdue: string;
  deliveryToday: string;
  deliveryDate: string;
  checkDelivery: string;
  poOrdered: string;
  poClosed: string;
  stockChange: string;
  quoteFallback: string;
  newQuote: string;
  invoiceFallback: string;
  newInvoice: string;
  voucherFallback: string;
  newVoucher: string;
  title: string;
  number: string;
  recipient: string;
  amount: string;
  contact: string;
  todoDone: string;
  todoDeferred: string;
  task: string;
  todoFallback: string;
  personalReminder: string;
  reminder: string;
  teamMessage: string;
  colleague: string;
  newMessageShort: string;
  contractSign: string;
  contractRevised: string;
  newContract: string;
  contractFallback: string;
  contractSignHint: string;
  contractViewHint: string;
  newDocument: string;
  documentFallback: string;
  timeCorrection: string;
  timeCorrectionSubject: string;
  kind: string;
  period: string;
  begin: string;
  pleaseApprove: string;
  displayClockIn: string;
  displayBreakStart: string;
  displayBreakEnd: string;
  displayAutoOut: string;
  displayClockOut: string;
  clockTime: string;
  autoOutHint: string;
  staffFallback: string;
  inviteAccepted: string;
  inviteDeclined: string;
  appRole: string;
  newRights: string;
  newModuleRights: string;
  role: string;
  openDashboard: string;
  changelogNew: string;
  changelog: string;
  published: string;
  version: string;
  email: string;
  phone: string;
  note: string;
  message: string;
  reservationNo: string;
  appointment: string;
  emailIntro: string;
  /** Trailing clock word, including the leading space. Empty when the locale has none. */
  clockSuffix: string;
  inviteAcceptedLine: string;
  inviteDeclinedLine: string;
  liveStill: string;
  liveLowStock: string;
  liveDeliveryDue: string;
  liveNewReservation: string;
  liveReservationChange: string;
  liveLoggedIn: string;
  liveLoggedOut: string;
  liveBreakStart: string;
  liveBreakEnd: string;
  liveShiftStart: string;
  liveShiftEnd: string;
  bellThreshold: string;
};

const DE: Phrase = {
  newMessage: "Neue Nachricht",
  channel: "Kanal",
  received: "Empfangen",
  followUpDue: "Später-Erinnerung fällig",
  later: "Später",
  chat: "Chat",
  reason: "Grund",
  due: "Fällig",
  guest: "Gast",
  messageFallback: "Nachricht",
  newReview: "Neue Bewertung",
  from: "Von",
  rating: "Bewertung",
  reviewedOn: "Bewertet am",
  newPendingReservation: "Neue unbestätigte Reservierung",
  newReservation: "Neue Reservierung",
  changeRequest: "Änderungsanfrage zur Reservierung",
  changeRequestShort: "Änderungsanfrage",
  cancellation: "Stornierung einer Reservierung",
  cancellationShort: "Stornierung",
  eventInquiry: "Neue Veranstaltungs-Anfrage",
  eventInquiryShort: "Veranstaltungs-Anfrage",
  company: "Firma",
  shiftStart: "Schichtbeginn",
  shiftEnd: "Schichtende",
  staff: "Mitarbeiter",
  shift: "Schicht",
  time: "Zeit",
  start: "Beginn",
  planned: "Geplant",
  end: "Ende",
  lowStock: "Niedrigbestand",
  ingredient: "Zutat",
  ingredientFallback: "Zutat",
  stock: "Bestand",
  threshold: "Schwelle",
  supplier: "Lieferant",
  supplierFallback: "Lieferant",
  overdue: "Überfällig",
  deliveryToday: "Lieferung heute",
  deliveryDate: "Lieferdatum",
  checkDelivery: "Bitte Lieferung prüfen und Bestellung abschließen.",
  poOrdered: "Bestellung aufgegeben",
  poClosed: "Bestellung abgeschlossen",
  stockChange: "Bestandsveränderung",
  quoteFallback: "Neues Angebot",
  newQuote: "Neues Angebot",
  invoiceFallback: "Neue Rechnung",
  newInvoice: "Neue Rechnung",
  voucherFallback: "Beleg",
  newVoucher: "Neuer Beleg",
  title: "Titel",
  number: "Nummer",
  recipient: "Empfänger",
  amount: "Betrag",
  contact: "Kontakt",
  todoDone: "ToDo erledigt",
  todoDeferred: "ToDo verschoben",
  task: "Aufgabe",
  todoFallback: "ToDo",
  personalReminder: "Persönliche Erinnerung",
  reminder: "Erinnerung",
  teamMessage: "Team-Nachricht",
  colleague: "Kollege",
  newMessageShort: "Neue Nachricht",
  contractSign: "Vertrag unterschreiben",
  contractRevised: "Vertrag überarbeitet",
  newContract: "Neuer Arbeitsvertrag",
  contractFallback: "Arbeitsvertrag",
  contractSignHint: "Bitte im Profil unter „Meine Dokumente“ unterschreiben.",
  contractViewHint: "Im Profil unter „Meine Dokumente“ einsehbar und herunterladbar.",
  newDocument: "Neues Dokument",
  documentFallback: "Dokument",
  timeCorrection: "Zeit nachtragen",
  timeCorrectionSubject: "Nachtragungs-Anfrage vom Display",
  kind: "Art",
  period: "Zeitraum",
  begin: "Beginn",
  pleaseApprove: "Bitte im Mitarbeiter-Dashboard prüfen und freigeben.",
  displayClockIn: "Display: Schicht gestartet",
  displayBreakStart: "Display: Pause gestartet",
  displayBreakEnd: "Display: Pause beendet",
  displayAutoOut: "Display: Auto-Abmeldung",
  displayClockOut: "Display: Schicht beendet",
  clockTime: "Uhrzeit",
  autoOutHint: "Hinweis: Auto-Abmeldung",
  staffFallback: "Mitarbeiter",
  inviteAccepted: "Einladung angenommen",
  inviteDeclined: "Einladung abgelehnt",
  appRole: "App-Rolle",
  newRights: "Neue Rechte freigeschaltet",
  newModuleRights: "Neue Modul-Rechte",
  role: "Rolle",
  openDashboard: "Öffne das Dashboard — deine neuen Möglichkeiten warten.",
  changelogNew: "Neu im Changelog",
  changelog: "Changelog",
  published: "Veröffentlicht",
  version: "Version",
  email: "E-Mail",
  phone: "Telefon",
  note: "Hinweis",
  message: "Nachricht",
  reservationNo: "Reservierung Nr.",
  appointment: "Termin",
  emailIntro: "Du hast eine neue Benachrichtigung in gwada.",
  clockSuffix: " Uhr",
  inviteAcceptedLine: "{name} hat die Einladung angenommen.",
  inviteDeclinedLine: "{name} hat die Einladung abgelehnt.",
  liveStill: "noch",
  liveLowStock: "Bestand niedrig",
  liveDeliveryDue: "Lieferung fällig",
  liveNewReservation: "Neue Reservierung",
  liveReservationChange: "Reservierungsänderung",
  liveLoggedIn: "angemeldet",
  liveLoggedOut: "abgemeldet",
  liveBreakStart: "Pause gestartet",
  liveBreakEnd: "Pause beendet",
  liveShiftStart: "Schichtstart",
  liveShiftEnd: "Schichtende",
  bellThreshold: "Schwelle",
};

const EN: Phrase = {
  newMessage: "New message",
  channel: "Channel",
  received: "Received",
  followUpDue: "Follow-up reminder due",
  later: "Later",
  chat: "Chat",
  reason: "Reason",
  due: "Due",
  guest: "Guest",
  messageFallback: "Message",
  newReview: "New review",
  from: "From",
  rating: "Rating",
  reviewedOn: "Reviewed on",
  newPendingReservation: "New unconfirmed reservation",
  newReservation: "New reservation",
  changeRequest: "Reservation change request",
  changeRequestShort: "Change request",
  cancellation: "Reservation cancellation",
  cancellationShort: "Cancellation",
  eventInquiry: "New event inquiry",
  eventInquiryShort: "Event inquiry",
  company: "Company",
  shiftStart: "Shift start",
  shiftEnd: "Shift end",
  staff: "Staff",
  shift: "Shift",
  time: "Time",
  start: "Start",
  planned: "Planned",
  end: "End",
  lowStock: "Low stock",
  ingredient: "Ingredient",
  ingredientFallback: "Ingredient",
  stock: "Stock",
  threshold: "Threshold",
  supplier: "Supplier",
  supplierFallback: "Supplier",
  overdue: "Overdue",
  deliveryToday: "Delivery today",
  deliveryDate: "Delivery date",
  checkDelivery: "Please check the delivery and close the order.",
  poOrdered: "Order placed",
  poClosed: "Order closed",
  stockChange: "Stock change",
  quoteFallback: "New quote",
  newQuote: "New quote",
  invoiceFallback: "New invoice",
  newInvoice: "New invoice",
  voucherFallback: "Receipt",
  newVoucher: "New receipt",
  title: "Title",
  number: "Number",
  recipient: "Recipient",
  amount: "Amount",
  contact: "Contact",
  todoDone: "To-do done",
  todoDeferred: "To-do postponed",
  task: "Task",
  todoFallback: "To-do",
  personalReminder: "Personal reminder",
  reminder: "Reminder",
  teamMessage: "Team message",
  colleague: "Colleague",
  newMessageShort: "New message",
  contractSign: "Sign contract",
  contractRevised: "Contract revised",
  newContract: "New employment contract",
  contractFallback: "Employment contract",
  contractSignHint: "Please sign it in your profile under “My documents”.",
  contractViewHint: "Available in your profile under “My documents”.",
  newDocument: "New document",
  documentFallback: "Document",
  timeCorrection: "Add time",
  timeCorrectionSubject: "Time-entry request from the display",
  kind: "Type",
  period: "Period",
  begin: "Start",
  pleaseApprove: "Please review and approve it in the staff dashboard.",
  displayClockIn: "Display: shift started",
  displayBreakStart: "Display: break started",
  displayBreakEnd: "Display: break ended",
  displayAutoOut: "Display: automatic clock-out",
  displayClockOut: "Display: shift ended",
  clockTime: "Time",
  autoOutHint: "Note: automatic clock-out",
  staffFallback: "Staff",
  inviteAccepted: "Invitation accepted",
  inviteDeclined: "Invitation declined",
  appRole: "App role",
  newRights: "New permissions unlocked",
  newModuleRights: "New module permissions",
  role: "Role",
  openDashboard: "Open the dashboard — your new options are waiting.",
  changelogNew: "New in the changelog",
  changelog: "Changelog",
  published: "Published",
  version: "Version",
  email: "Email",
  phone: "Phone",
  note: "Note",
  message: "Message",
  reservationNo: "Reservation no.",
  appointment: "Appointment",
  emailIntro: "You have a new notification in gwada.",
  clockSuffix: "",
  inviteAcceptedLine: "{name} accepted the invitation.",
  inviteDeclinedLine: "{name} declined the invitation.",
  liveStill: "left",
  liveLowStock: "Stock low",
  liveDeliveryDue: "Delivery due",
  liveNewReservation: "New reservation",
  liveReservationChange: "Reservation change",
  liveLoggedIn: "clocked in",
  liveLoggedOut: "clocked out",
  liveBreakStart: "break started",
  liveBreakEnd: "break ended",
  liveShiftStart: "shift start",
  liveShiftEnd: "shift end",
  bellThreshold: "threshold",
};

const ES: Phrase = {
  ...EN,
  newMessage: "Nuevo mensaje",
  channel: "Canal",
  received: "Recibido",
  followUpDue: "Recordatorio pendiente",
  later: "Más tarde",
  chat: "Chat",
  reason: "Motivo",
  due: "Vence",
  guest: "Cliente",
  messageFallback: "Mensaje",
  newReview: "Nueva reseña",
  from: "De",
  rating: "Valoración",
  reviewedOn: "Valorada el",
  newPendingReservation: "Nueva reserva sin confirmar",
  newReservation: "Nueva reserva",
  changeRequest: "Solicitud de cambio de reserva",
  changeRequestShort: "Solicitud de cambio",
  cancellation: "Cancelación de una reserva",
  cancellationShort: "Cancelación",
  eventInquiry: "Nueva consulta de evento",
  eventInquiryShort: "Consulta de evento",
  company: "Empresa",
  shiftStart: "Inicio de turno",
  shiftEnd: "Fin de turno",
  staff: "Empleado",
  shift: "Turno",
  time: "Hora",
  start: "Inicio",
  planned: "Previsto",
  end: "Fin",
  lowStock: "Stock bajo",
  ingredient: "Ingrediente",
  ingredientFallback: "Ingrediente",
  stock: "Stock",
  threshold: "Umbral",
  supplier: "Proveedor",
  supplierFallback: "Proveedor",
  overdue: "Atrasada",
  deliveryToday: "Entrega hoy",
  deliveryDate: "Fecha de entrega",
  checkDelivery: "Revisa la entrega y cierra el pedido.",
  poOrdered: "Pedido realizado",
  poClosed: "Pedido cerrado",
  stockChange: "Cambio de stock",
  quoteFallback: "Nuevo presupuesto",
  newQuote: "Nuevo presupuesto",
  invoiceFallback: "Nueva factura",
  newInvoice: "Nueva factura",
  voucherFallback: "Comprobante",
  newVoucher: "Nuevo comprobante",
  title: "Título",
  number: "Número",
  recipient: "Destinatario",
  amount: "Importe",
  contact: "Contacto",
  todoDone: "Tarea hecha",
  todoDeferred: "Tarea aplazada",
  task: "Tarea",
  todoFallback: "Tarea",
  personalReminder: "Recordatorio personal",
  reminder: "Recordatorio",
  teamMessage: "Mensaje de equipo",
  colleague: "Compañero",
  newMessageShort: "Nuevo mensaje",
  contractSign: "Firmar contrato",
  contractRevised: "Contrato revisado",
  newContract: "Nuevo contrato",
  contractFallback: "Contrato",
  contractSignHint: "Fírmalo en tu perfil, en “Mis documentos”.",
  contractViewHint: "Disponible en tu perfil, en “Mis documentos”.",
  newDocument: "Nuevo documento",
  documentFallback: "Documento",
  timeCorrection: "Añadir tiempo",
  timeCorrectionSubject: "Solicitud de fichaje desde la pantalla",
  kind: "Tipo",
  period: "Periodo",
  begin: "Inicio",
  pleaseApprove: "Revísala y apruébala en el panel de personal.",
  displayClockIn: "Pantalla: turno iniciado",
  displayBreakStart: "Pantalla: pausa iniciada",
  displayBreakEnd: "Pantalla: pausa terminada",
  displayAutoOut: "Pantalla: salida automática",
  displayClockOut: "Pantalla: turno terminado",
  clockTime: "Hora",
  autoOutHint: "Nota: salida automática",
  staffFallback: "Empleado",
  inviteAccepted: "Invitación aceptada",
  inviteDeclined: "Invitación rechazada",
  appRole: "Rol en la app",
  newRights: "Nuevos permisos",
  newModuleRights: "Nuevos permisos de módulo",
  role: "Rol",
  openDashboard: "Abre el panel: tus nuevas opciones te esperan.",
  changelogNew: "Novedad en el registro",
  changelog: "Registro de cambios",
  published: "Publicado",
  version: "Versión",
  email: "Correo",
  phone: "Teléfono",
  note: "Nota",
  message: "Mensaje",
  reservationNo: "Reserva n.º",
  appointment: "Cita",
  emailIntro: "Tienes un aviso nuevo en gwada.",
  inviteAcceptedLine: "{name} ha aceptado la invitación.",
  inviteDeclinedLine: "{name} ha rechazado la invitación.",
  liveStill: "quedan",
  liveLowStock: "Stock bajo",
  liveDeliveryDue: "Entrega pendiente",
  liveNewReservation: "Nueva reserva",
  liveReservationChange: "Cambio de reserva",
  liveLoggedIn: "ha fichado",
  liveLoggedOut: "ha salido",
  liveBreakStart: "pausa iniciada",
  liveBreakEnd: "pausa terminada",
  liveShiftStart: "inicio de turno",
  liveShiftEnd: "fin de turno",
  bellThreshold: "umbral",
};

const FR: Phrase = {
  ...EN,
  newMessage: "Nouveau message",
  channel: "Canal",
  received: "Reçu",
  followUpDue: "Rappel à traiter",
  later: "Plus tard",
  chat: "Discussion",
  reason: "Motif",
  due: "Échéance",
  guest: "Client",
  messageFallback: "Message",
  newReview: "Nouvel avis",
  from: "De",
  rating: "Note",
  reviewedOn: "Avis du",
  newPendingReservation: "Nouvelle réservation non confirmée",
  newReservation: "Nouvelle réservation",
  changeRequest: "Demande de modification",
  changeRequestShort: "Demande de modification",
  cancellation: "Annulation d’une réservation",
  cancellationShort: "Annulation",
  eventInquiry: "Nouvelle demande d’événement",
  eventInquiryShort: "Demande d’événement",
  company: "Société",
  shiftStart: "Début de service",
  shiftEnd: "Fin de service",
  staff: "Employé",
  shift: "Service",
  time: "Horaire",
  start: "Début",
  planned: "Prévu",
  end: "Fin",
  lowStock: "Stock bas",
  ingredient: "Ingrédient",
  ingredientFallback: "Ingrédient",
  stock: "Stock",
  threshold: "Seuil",
  supplier: "Fournisseur",
  supplierFallback: "Fournisseur",
  overdue: "En retard",
  deliveryToday: "Livraison aujourd’hui",
  deliveryDate: "Date de livraison",
  checkDelivery: "Vérifie la livraison et clôture la commande.",
  poOrdered: "Commande passée",
  poClosed: "Commande clôturée",
  stockChange: "Variation de stock",
  quoteFallback: "Nouveau devis",
  newQuote: "Nouveau devis",
  invoiceFallback: "Nouvelle facture",
  newInvoice: "Nouvelle facture",
  voucherFallback: "Justificatif",
  newVoucher: "Nouveau justificatif",
  title: "Titre",
  number: "Numéro",
  recipient: "Destinataire",
  amount: "Montant",
  contact: "Contact",
  todoDone: "Tâche faite",
  todoDeferred: "Tâche reportée",
  task: "Tâche",
  todoFallback: "Tâche",
  personalReminder: "Rappel personnel",
  reminder: "Rappel",
  teamMessage: "Message d’équipe",
  colleague: "Collègue",
  newMessageShort: "Nouveau message",
  contractSign: "Signer le contrat",
  contractRevised: "Contrat révisé",
  newContract: "Nouveau contrat",
  contractFallback: "Contrat",
  contractSignHint: "Signe-le dans ton profil, sous « Mes documents ».",
  contractViewHint: "Disponible dans ton profil, sous « Mes documents ».",
  newDocument: "Nouveau document",
  documentFallback: "Document",
  timeCorrection: "Ajouter un horaire",
  timeCorrectionSubject: "Demande d’horaire depuis l’écran",
  kind: "Type",
  period: "Période",
  begin: "Début",
  pleaseApprove: "Vérifie et valide dans le tableau du personnel.",
  displayClockIn: "Écran : service commencé",
  displayBreakStart: "Écran : pause commencée",
  displayBreakEnd: "Écran : pause terminée",
  displayAutoOut: "Écran : départ automatique",
  displayClockOut: "Écran : service terminé",
  clockTime: "Heure",
  autoOutHint: "Note : départ automatique",
  staffFallback: "Employé",
  inviteAccepted: "Invitation acceptée",
  inviteDeclined: "Invitation refusée",
  appRole: "Rôle dans l’app",
  newRights: "Nouveaux droits",
  newModuleRights: "Nouveaux droits de module",
  role: "Rôle",
  openDashboard: "Ouvre le tableau de bord — tes nouvelles options t’attendent.",
  changelogNew: "Nouveau dans le journal",
  changelog: "Journal des changements",
  published: "Publié",
  version: "Version",
  email: "E-mail",
  phone: "Téléphone",
  note: "Note",
  message: "Message",
  reservationNo: "Réservation n°",
  appointment: "Rendez-vous",
  emailIntro: "Tu as une nouvelle notification dans gwada.",
  inviteAcceptedLine: "{name} a accepté l’invitation.",
  inviteDeclinedLine: "{name} a refusé l’invitation.",
  liveStill: "reste",
  liveLowStock: "Stock bas",
  liveDeliveryDue: "Livraison à faire",
  liveNewReservation: "Nouvelle réservation",
  liveReservationChange: "Modification de réservation",
  liveLoggedIn: "connecté",
  liveLoggedOut: "déconnecté",
  liveBreakStart: "pause commencée",
  liveBreakEnd: "pause terminée",
  liveShiftStart: "début de service",
  liveShiftEnd: "fin de service",
  bellThreshold: "seuil",
};

const IT: Phrase = {
  ...EN,
  newMessage: "Nuovo messaggio",
  channel: "Canale",
  received: "Ricevuto",
  followUpDue: "Promemoria in scadenza",
  later: "Più tardi",
  chat: "Chat",
  reason: "Motivo",
  due: "Scadenza",
  guest: "Ospite",
  messageFallback: "Messaggio",
  newReview: "Nuova recensione",
  from: "Da",
  rating: "Valutazione",
  reviewedOn: "Recensito il",
  newPendingReservation: "Nuova prenotazione non confermata",
  newReservation: "Nuova prenotazione",
  changeRequest: "Richiesta di modifica",
  changeRequestShort: "Richiesta di modifica",
  cancellation: "Annullamento di una prenotazione",
  cancellationShort: "Annullamento",
  eventInquiry: "Nuova richiesta evento",
  eventInquiryShort: "Richiesta evento",
  company: "Azienda",
  shiftStart: "Inizio turno",
  shiftEnd: "Fine turno",
  staff: "Collaboratore",
  shift: "Turno",
  time: "Orario",
  start: "Inizio",
  planned: "Previsto",
  end: "Fine",
  lowStock: "Scorte basse",
  ingredient: "Ingrediente",
  ingredientFallback: "Ingrediente",
  stock: "Scorte",
  threshold: "Soglia",
  supplier: "Fornitore",
  supplierFallback: "Fornitore",
  overdue: "In ritardo",
  deliveryToday: "Consegna oggi",
  deliveryDate: "Data di consegna",
  checkDelivery: "Controlla la consegna e chiudi l’ordine.",
  poOrdered: "Ordine inviato",
  poClosed: "Ordine chiuso",
  stockChange: "Variazione di scorta",
  quoteFallback: "Nuovo preventivo",
  newQuote: "Nuovo preventivo",
  invoiceFallback: "Nuova fattura",
  newInvoice: "Nuova fattura",
  voucherFallback: "Giustificativo",
  newVoucher: "Nuovo giustificativo",
  title: "Titolo",
  number: "Numero",
  recipient: "Destinatario",
  amount: "Importo",
  contact: "Contatto",
  todoDone: "Attività completata",
  todoDeferred: "Attività rinviata",
  task: "Attività",
  todoFallback: "Attività",
  personalReminder: "Promemoria personale",
  reminder: "Promemoria",
  teamMessage: "Messaggio del team",
  colleague: "Collega",
  newMessageShort: "Nuovo messaggio",
  contractSign: "Firma il contratto",
  contractRevised: "Contratto rivisto",
  newContract: "Nuovo contratto",
  contractFallback: "Contratto",
  contractSignHint: "Firmalo nel profilo, sotto “I miei documenti”.",
  contractViewHint: "Disponibile nel profilo, sotto “I miei documenti”.",
  newDocument: "Nuovo documento",
  documentFallback: "Documento",
  timeCorrection: "Aggiungi orario",
  timeCorrectionSubject: "Richiesta orario dal display",
  kind: "Tipo",
  period: "Periodo",
  begin: "Inizio",
  pleaseApprove: "Controlla e approva nella bacheca del personale.",
  displayClockIn: "Display: turno iniziato",
  displayBreakStart: "Display: pausa iniziata",
  displayBreakEnd: "Display: pausa terminata",
  displayAutoOut: "Display: uscita automatica",
  displayClockOut: "Display: turno terminato",
  clockTime: "Ora",
  autoOutHint: "Nota: uscita automatica",
  staffFallback: "Collaboratore",
  inviteAccepted: "Invito accettato",
  inviteDeclined: "Invito rifiutato",
  appRole: "Ruolo nell’app",
  newRights: "Nuovi permessi",
  newModuleRights: "Nuovi permessi di modulo",
  role: "Ruolo",
  openDashboard: "Apri la bacheca: le nuove funzioni ti aspettano.",
  changelogNew: "Novità nel registro",
  changelog: "Registro modifiche",
  published: "Pubblicato",
  version: "Versione",
  email: "Email",
  phone: "Telefono",
  note: "Nota",
  message: "Messaggio",
  reservationNo: "Prenotazione n.",
  appointment: "Appuntamento",
  emailIntro: "Hai una nuova notifica in gwada.",
  inviteAcceptedLine: "{name} ha accettato l’invito.",
  inviteDeclinedLine: "{name} ha rifiutato l’invito.",
  liveStill: "rimasti",
  liveLowStock: "Scorte basse",
  liveDeliveryDue: "Consegna in scadenza",
  liveNewReservation: "Nuova prenotazione",
  liveReservationChange: "Modifica prenotazione",
  liveLoggedIn: "entrato",
  liveLoggedOut: "uscito",
  liveBreakStart: "pausa iniziata",
  liveBreakEnd: "pausa terminata",
  liveShiftStart: "inizio turno",
  liveShiftEnd: "fine turno",
  bellThreshold: "soglia",
};

const TR: Phrase = {
  ...EN,
  newMessage: "Yeni mesaj",
  channel: "Kanal",
  received: "Alındı",
  followUpDue: "Sonra hatırlatması geldi",
  later: "Sonra",
  chat: "Sohbet",
  reason: "Gerekçe",
  due: "Vade",
  guest: "Misafir",
  messageFallback: "Mesaj",
  newReview: "Yeni değerlendirme",
  from: "Kimden",
  rating: "Puan",
  reviewedOn: "Değerlendirme tarihi",
  newPendingReservation: "Onaylanmamış yeni rezervasyon",
  newReservation: "Yeni rezervasyon",
  changeRequest: "Rezervasyon değişiklik isteği",
  changeRequestShort: "Değişiklik isteği",
  cancellation: "Rezervasyon iptali",
  cancellationShort: "İptal",
  eventInquiry: "Yeni etkinlik talebi",
  eventInquiryShort: "Etkinlik talebi",
  company: "Firma",
  shiftStart: "Vardiya başlangıcı",
  shiftEnd: "Vardiya bitişi",
  staff: "Çalışan",
  shift: "Vardiya",
  time: "Saat",
  start: "Başlangıç",
  planned: "Planlanan",
  end: "Bitiş",
  lowStock: "Düşük stok",
  ingredient: "Malzeme",
  ingredientFallback: "Malzeme",
  stock: "Stok",
  threshold: "Eşik",
  supplier: "Tedarikçi",
  supplierFallback: "Tedarikçi",
  overdue: "Gecikmiş",
  deliveryToday: "Bugün teslimat",
  deliveryDate: "Teslimat tarihi",
  checkDelivery: "Teslimatı kontrol edip siparişi kapat.",
  poOrdered: "Sipariş verildi",
  poClosed: "Sipariş kapandı",
  stockChange: "Stok değişikliği",
  quoteFallback: "Yeni teklif",
  newQuote: "Yeni teklif",
  invoiceFallback: "Yeni fatura",
  newInvoice: "Yeni fatura",
  voucherFallback: "Belge",
  newVoucher: "Yeni belge",
  title: "Başlık",
  number: "Numara",
  recipient: "Alıcı",
  amount: "Tutar",
  contact: "Kişi",
  todoDone: "Görev bitti",
  todoDeferred: "Görev ertelendi",
  task: "Görev",
  todoFallback: "Görev",
  personalReminder: "Kişisel hatırlatma",
  reminder: "Hatırlatma",
  teamMessage: "Ekip mesajı",
  colleague: "Meslektaş",
  newMessageShort: "Yeni mesaj",
  contractSign: "Sözleşmeyi imzala",
  contractRevised: "Sözleşme güncellendi",
  newContract: "Yeni iş sözleşmesi",
  contractFallback: "İş sözleşmesi",
  contractSignHint: "Profilinde “Belgelerim” altında imzala.",
  contractViewHint: "Profilinde “Belgelerim” altında görülebilir.",
  newDocument: "Yeni belge",
  documentFallback: "Belge",
  timeCorrection: "Süre ekle",
  timeCorrectionSubject: "Ekrandan süre talebi",
  kind: "Tür",
  period: "Dönem",
  begin: "Başlangıç",
  pleaseApprove: "Personel panelinde kontrol edip onayla.",
  displayClockIn: "Ekran: vardiya başladı",
  displayBreakStart: "Ekran: mola başladı",
  displayBreakEnd: "Ekran: mola bitti",
  displayAutoOut: "Ekran: otomatik çıkış",
  displayClockOut: "Ekran: vardiya bitti",
  clockTime: "Saat",
  autoOutHint: "Not: otomatik çıkış",
  staffFallback: "Çalışan",
  inviteAccepted: "Davet kabul edildi",
  inviteDeclined: "Davet reddedildi",
  appRole: "Uygulama rolü",
  newRights: "Yeni yetkiler",
  newModuleRights: "Yeni modül yetkileri",
  role: "Rol",
  openDashboard: "Paneli aç — yeni olanakların hazır.",
  changelogNew: "Değişiklik günlüğünde yeni",
  changelog: "Değişiklik günlüğü",
  published: "Yayınlandı",
  version: "Sürüm",
  email: "E-posta",
  phone: "Telefon",
  note: "Not",
  message: "Mesaj",
  reservationNo: "Rezervasyon no.",
  appointment: "Randevu",
  emailIntro: "gwada’da yeni bir bildirimin var.",
  inviteAcceptedLine: "{name} daveti kabul etti.",
  inviteDeclinedLine: "{name} daveti reddetti.",
  liveStill: "kaldı",
  liveLowStock: "Stok düşük",
  liveDeliveryDue: "Teslimat zamanı",
  liveNewReservation: "Yeni rezervasyon",
  liveReservationChange: "Rezervasyon değişikliği",
  liveLoggedIn: "giriş yaptı",
  liveLoggedOut: "çıkış yaptı",
  liveBreakStart: "mola başladı",
  liveBreakEnd: "mola bitti",
  liveShiftStart: "vardiya başlangıcı",
  liveShiftEnd: "vardiya bitişi",
  bellThreshold: "eşik",
};

const AR: Phrase = {
  ...EN,
  newMessage: "رسالة جديدة",
  channel: "القناة",
  received: "استُلمت",
  followUpDue: "تذكير لاحق مستحق",
  later: "لاحقاً",
  chat: "المحادثة",
  reason: "السبب",
  due: "الاستحقاق",
  guest: "الضيف",
  messageFallback: "رسالة",
  newReview: "تقييم جديد",
  from: "من",
  rating: "التقييم",
  reviewedOn: "تاريخ التقييم",
  newPendingReservation: "حجز جديد غير مؤكد",
  newReservation: "حجز جديد",
  changeRequest: "طلب تعديل الحجز",
  changeRequestShort: "طلب تعديل",
  cancellation: "إلغاء حجز",
  cancellationShort: "إلغاء",
  eventInquiry: "طلب مناسبة جديد",
  eventInquiryShort: "طلب مناسبة",
  company: "الشركة",
  shiftStart: "بداية الوردية",
  shiftEnd: "نهاية الوردية",
  staff: "الموظف",
  shift: "الوردية",
  time: "الوقت",
  start: "البداية",
  planned: "المخطط",
  end: "النهاية",
  lowStock: "مخزون منخفض",
  ingredient: "مكوّن",
  ingredientFallback: "مكوّن",
  stock: "المخزون",
  threshold: "الحد",
  supplier: "المورّد",
  supplierFallback: "المورّد",
  overdue: "متأخر",
  deliveryToday: "تسليم اليوم",
  deliveryDate: "تاريخ التسليم",
  checkDelivery: "راجع التسليم وأغلق الطلب.",
  poOrdered: "تم الطلب",
  poClosed: "أُغلق الطلب",
  stockChange: "تغيّر المخزون",
  quoteFallback: "عرض جديد",
  newQuote: "عرض جديد",
  invoiceFallback: "فاتورة جديدة",
  newInvoice: "فاتورة جديدة",
  voucherFallback: "مستند",
  newVoucher: "مستند جديد",
  title: "العنوان",
  number: "الرقم",
  recipient: "المستلم",
  amount: "المبلغ",
  contact: "جهة الاتصال",
  todoDone: "مهمة منجزة",
  todoDeferred: "مهمة مؤجلة",
  task: "المهمة",
  todoFallback: "مهمة",
  personalReminder: "تذكير شخصي",
  reminder: "تذكير",
  teamMessage: "رسالة الفريق",
  colleague: "زميل",
  newMessageShort: "رسالة جديدة",
  contractSign: "وقّع العقد",
  contractRevised: "تم تعديل العقد",
  newContract: "عقد عمل جديد",
  contractFallback: "عقد عمل",
  contractSignHint: "وقّعه في ملفك تحت «مستنداتي».",
  contractViewHint: "متاح في ملفك تحت «مستنداتي».",
  newDocument: "مستند جديد",
  documentFallback: "مستند",
  timeCorrection: "إضافة وقت",
  timeCorrectionSubject: "طلب وقت من الشاشة",
  kind: "النوع",
  period: "الفترة",
  begin: "البداية",
  pleaseApprove: "راجعه ووافق عليه في لوحة الموظفين.",
  displayClockIn: "الشاشة: بدأت الوردية",
  displayBreakStart: "الشاشة: بدأت الاستراحة",
  displayBreakEnd: "الشاشة: انتهت الاستراحة",
  displayAutoOut: "الشاشة: خروج تلقائي",
  displayClockOut: "الشاشة: انتهت الوردية",
  clockTime: "الوقت",
  autoOutHint: "ملاحظة: خروج تلقائي",
  staffFallback: "الموظف",
  inviteAccepted: "تم قبول الدعوة",
  inviteDeclined: "تم رفض الدعوة",
  appRole: "الدور في التطبيق",
  newRights: "صلاحيات جديدة",
  newModuleRights: "صلاحيات وحدات جديدة",
  role: "الدور",
  openDashboard: "افتح اللوحة — خياراتك الجديدة بانتظارك.",
  changelogNew: "جديد في سجل التغييرات",
  changelog: "سجل التغييرات",
  published: "نُشر",
  version: "الإصدار",
  email: "البريد",
  phone: "الهاتف",
  note: "ملاحظة",
  message: "رسالة",
  reservationNo: "رقم الحجز",
  appointment: "الموعد",
  emailIntro: "لديك إشعار جديد في gwada.",
  inviteAcceptedLine: "قبل {name} الدعوة.",
  inviteDeclinedLine: "رفض {name} الدعوة.",
  liveStill: "متبقٍ",
  liveLowStock: "المخزون منخفض",
  liveDeliveryDue: "تسليم مستحق",
  liveNewReservation: "حجز جديد",
  liveReservationChange: "تعديل حجز",
  liveLoggedIn: "سجّل الدخول",
  liveLoggedOut: "سجّل الخروج",
  liveBreakStart: "بدأت الاستراحة",
  liveBreakEnd: "انتهت الاستراحة",
  liveShiftStart: "بداية الوردية",
  liveShiftEnd: "نهاية الوردية",
  bellThreshold: "الحد",
};

const ZH: Phrase = {
  ...EN,
  newMessage: "新消息",
  channel: "渠道",
  received: "收到",
  followUpDue: "稍后提醒到期",
  later: "稍后",
  chat: "对话",
  reason: "原因",
  due: "到期",
  guest: "客人",
  messageFallback: "消息",
  newReview: "新评价",
  from: "来自",
  rating: "评分",
  reviewedOn: "评价时间",
  newPendingReservation: "新的未确认预订",
  newReservation: "新预订",
  changeRequest: "预订变更请求",
  changeRequestShort: "变更请求",
  cancellation: "预订取消",
  cancellationShort: "取消",
  eventInquiry: "新的活动咨询",
  eventInquiryShort: "活动咨询",
  company: "公司",
  shiftStart: "班次开始",
  shiftEnd: "班次结束",
  staff: "员工",
  shift: "班次",
  time: "时间",
  start: "开始",
  planned: "计划",
  end: "结束",
  lowStock: "库存偏低",
  ingredient: "原料",
  ingredientFallback: "原料",
  stock: "库存",
  threshold: "阈值",
  supplier: "供应商",
  supplierFallback: "供应商",
  overdue: "已逾期",
  deliveryToday: "今日到货",
  deliveryDate: "到货日期",
  checkDelivery: "请核对到货并完成订单。",
  poOrdered: "订单已下",
  poClosed: "订单已完成",
  stockChange: "库存变动",
  quoteFallback: "新报价",
  newQuote: "新报价",
  invoiceFallback: "新发票",
  newInvoice: "新发票",
  voucherFallback: "凭证",
  newVoucher: "新凭证",
  title: "标题",
  number: "编号",
  recipient: "收件人",
  amount: "金额",
  contact: "联系人",
  todoDone: "待办已完成",
  todoDeferred: "待办已推迟",
  task: "任务",
  todoFallback: "待办",
  personalReminder: "个人提醒",
  reminder: "提醒",
  teamMessage: "团队消息",
  colleague: "同事",
  newMessageShort: "新消息",
  contractSign: "签署合同",
  contractRevised: "合同已修订",
  newContract: "新劳动合同",
  contractFallback: "劳动合同",
  contractSignHint: "请在个人资料的“我的文档”中签署。",
  contractViewHint: "可在个人资料的“我的文档”中查看和下载。",
  newDocument: "新文档",
  documentFallback: "文档",
  timeCorrection: "补记时间",
  timeCorrectionSubject: "来自显示屏的补记请求",
  kind: "类型",
  period: "时段",
  begin: "开始",
  pleaseApprove: "请在员工面板中审核并批准。",
  displayClockIn: "显示屏：班次已开始",
  displayBreakStart: "显示屏：休息已开始",
  displayBreakEnd: "显示屏：休息已结束",
  displayAutoOut: "显示屏：自动签退",
  displayClockOut: "显示屏：班次已结束",
  clockTime: "时间",
  autoOutHint: "提示：自动签退",
  staffFallback: "员工",
  inviteAccepted: "已接受邀请",
  inviteDeclined: "已拒绝邀请",
  appRole: "应用角色",
  newRights: "新权限已开通",
  newModuleRights: "新的模块权限",
  role: "角色",
  openDashboard: "打开仪表板，新功能已就绪。",
  changelogNew: "更新日志中的新内容",
  changelog: "更新日志",
  published: "发布时间",
  version: "版本",
  email: "电子邮件",
  phone: "电话",
  note: "备注",
  message: "消息",
  reservationNo: "预订号",
  appointment: "时间",
  emailIntro: "你在 gwada 有一条新通知。",
  inviteAcceptedLine: "{name} 已接受邀请。",
  inviteDeclinedLine: "{name} 已拒绝邀请。",
  liveStill: "剩余",
  liveLowStock: "库存偏低",
  liveDeliveryDue: "到货到期",
  liveNewReservation: "新预订",
  liveReservationChange: "预订变更",
  liveLoggedIn: "已签到",
  liveLoggedOut: "已签退",
  liveBreakStart: "休息已开始",
  liveBreakEnd: "休息已结束",
  liveShiftStart: "班次开始",
  liveShiftEnd: "班次结束",
  bellThreshold: "阈值",
};

const PHRASES: Record<AppLocale, Phrase> = {
  de: DE,
  en: EN,
  es: ES,
  fr: FR,
  it: IT,
  tr: TR,
  ar: AR,
  zh: ZH,
};

const MODULES: Record<AppLocale, Record<NotificationModuleId, ModuleNoticeLabel>> = {
  de: moduleLabels({
    messages: ["Nachricht", "Nachrichten"],
    messages_follow_up: ["Nachricht später", "Später"],
    reviews: ["Bewertung", "Bewertungen"],
    changelog: ["Changelog", "Changelog"],
    reservations_pending: ["Unbestätigte Reservierung", "Unbestätigt"],
    reservations_change_request: ["Änderungsanfrage", "Änderungsanfragen"],
    reservations_cancellation: ["Stornierung", "Stornierungen"],
    reservations_activity: ["Reservierungsaktivität", "Reservierungsaktivität"],
    events_inquiry: ["Veranstaltungs-Anfrage", "Veranstaltungs-Anfragen"],
    staff_shift_start: ["Schichtbeginn", "Schichtbeginn"],
    staff_shift_end: ["Schichtende", "Schichtende"],
    inventory_low_stock: ["Niedrigbestand", "Niedrigbestand"],
    inventory_po_delivery_due: ["Lieferung fällig", "Lieferungen fällig"],
    inventory_po_ordered: ["Bestellung aufgegeben", "Bestellt"],
    inventory_po_closed: ["Bestellung abgeschlossen", "Abgeschlossen"],
    inventory_po_activity: ["Bestellung", "Bestellungen"],
    inventory_stock_activity: ["Bestand", "Bestand"],
    accounting_quotation: ["Angebot", "Angebote"],
    accounting_invoice: ["Rechnung", "Rechnungen"],
    accounting_voucher: ["Beleg", "Belege"],
    staff_todo_completed: ["ToDo erledigt", "ToDos erledigt"],
    staff_todo_deferred: ["ToDo verschoben", "ToDos verschoben"],
    personal_reminder: ["Persönliche Erinnerung", "Erinnerungen"],
    staff_messages: ["Team-Nachricht", "Team-Nachrichten"],
    staff_contract_signed: ["Arbeitsvertrag", "Arbeitsverträge"],
    staff_document_assigned: ["Dokument", "Dokumente"],
    staff_display_time_request: ["Zeit nachtragen", "Zeit nachtragen"],
    staff_invite_accepted: ["Einladung angenommen", "Einladungen angenommen"],
    staff_invite_declined: ["Einladung abgelehnt", "Einladungen abgelehnt"],
    staff_display_clock_in: ["Display-Schichtstart", "Display-Schichtstart"],
    staff_display_clock_out: ["Display-Schichtende", "Display-Schichtende"],
    staff_display_break_start: ["Pause gestartet", "Pause gestartet"],
    staff_display_break_end: ["Pause beendet", "Pause beendet"],
    staff_permissions_granted: ["Neue Rechte", "Neue Rechte"],
    digest_daily_preview: ["Tagesvorschau", "Tagesvorschau"],
    digest_daily_review: ["Tagesrückblick", "Tagesrückblick"],
    digest_weekly_preview: ["Wochenvorschau", "Wochenvorschau"],
    digest_weekly_review: ["Wochenrückblick", "Wochenrückblick"],
  }),
  en: moduleLabels({
    messages: ["Message", "Messages"],
    messages_follow_up: ["Message later", "Later"],
    reviews: ["Review", "Reviews"],
    changelog: ["Changelog", "Changelog"],
    reservations_pending: ["Unconfirmed reservation", "Unconfirmed"],
    reservations_change_request: ["Change request", "Change requests"],
    reservations_cancellation: ["Cancellation", "Cancellations"],
    reservations_activity: ["Reservation activity", "Reservation activity"],
    events_inquiry: ["Event inquiry", "Event inquiries"],
    staff_shift_start: ["Shift start", "Shift start"],
    staff_shift_end: ["Shift end", "Shift end"],
    inventory_low_stock: ["Low stock", "Low stock"],
    inventory_po_delivery_due: ["Delivery due", "Deliveries due"],
    inventory_po_ordered: ["Order placed", "Ordered"],
    inventory_po_closed: ["Order closed", "Closed"],
    inventory_po_activity: ["Order", "Orders"],
    inventory_stock_activity: ["Stock", "Stock"],
    accounting_quotation: ["Quote", "Quotes"],
    accounting_invoice: ["Invoice", "Invoices"],
    accounting_voucher: ["Receipt", "Receipts"],
    staff_todo_completed: ["To-do done", "To-dos done"],
    staff_todo_deferred: ["To-do postponed", "To-dos postponed"],
    personal_reminder: ["Personal reminder", "Reminders"],
    staff_messages: ["Team message", "Team messages"],
    staff_contract_signed: ["Contract", "Contracts"],
    staff_document_assigned: ["Document", "Documents"],
    staff_display_time_request: ["Add time", "Add time"],
    staff_invite_accepted: ["Invitation accepted", "Invitations accepted"],
    staff_invite_declined: ["Invitation declined", "Invitations declined"],
    staff_display_clock_in: ["Display clock-in", "Display clock-in"],
    staff_display_clock_out: ["Display clock-out", "Display clock-out"],
    staff_display_break_start: ["Break started", "Break started"],
    staff_display_break_end: ["Break ended", "Break ended"],
    staff_permissions_granted: ["New permissions", "New permissions"],
    digest_daily_preview: ["Daily preview", "Daily preview"],
    digest_daily_review: ["Daily review", "Daily review"],
    digest_weekly_preview: ["Weekly preview", "Weekly preview"],
    digest_weekly_review: ["Weekly review", "Weekly review"],
  }),
  es: moduleLabels({
    messages: ["Mensaje", "Mensajes"],
    messages_follow_up: ["Mensaje más tarde", "Más tarde"],
    reviews: ["Reseña", "Reseñas"],
    changelog: ["Registro", "Registro"],
    reservations_pending: ["Reserva sin confirmar", "Sin confirmar"],
    reservations_change_request: ["Solicitud de cambio", "Solicitudes de cambio"],
    reservations_cancellation: ["Cancelación", "Cancelaciones"],
    reservations_activity: ["Actividad de reservas", "Actividad de reservas"],
    events_inquiry: ["Consulta de evento", "Consultas de evento"],
    staff_shift_start: ["Inicio de turno", "Inicio de turno"],
    staff_shift_end: ["Fin de turno", "Fin de turno"],
    inventory_low_stock: ["Stock bajo", "Stock bajo"],
    inventory_po_delivery_due: ["Entrega pendiente", "Entregas pendientes"],
    inventory_po_ordered: ["Pedido realizado", "Pedidos"],
    inventory_po_closed: ["Pedido cerrado", "Cerrados"],
    inventory_po_activity: ["Pedido", "Pedidos"],
    inventory_stock_activity: ["Stock", "Stock"],
    accounting_quotation: ["Presupuesto", "Presupuestos"],
    accounting_invoice: ["Factura", "Facturas"],
    accounting_voucher: ["Comprobante", "Comprobantes"],
    staff_todo_completed: ["Tarea hecha", "Tareas hechas"],
    staff_todo_deferred: ["Tarea aplazada", "Tareas aplazadas"],
    personal_reminder: ["Recordatorio personal", "Recordatorios"],
    staff_messages: ["Mensaje de equipo", "Mensajes de equipo"],
    staff_contract_signed: ["Contrato", "Contratos"],
    staff_document_assigned: ["Documento", "Documentos"],
    staff_display_time_request: ["Añadir tiempo", "Añadir tiempo"],
    staff_invite_accepted: ["Invitación aceptada", "Invitaciones aceptadas"],
    staff_invite_declined: ["Invitación rechazada", "Invitaciones rechazadas"],
    staff_display_clock_in: ["Entrada en pantalla", "Entrada en pantalla"],
    staff_display_clock_out: ["Salida en pantalla", "Salida en pantalla"],
    staff_display_break_start: ["Pausa iniciada", "Pausa iniciada"],
    staff_display_break_end: ["Pausa terminada", "Pausa terminada"],
    staff_permissions_granted: ["Nuevos permisos", "Nuevos permisos"],
    digest_daily_preview: ["Avance del día", "Avance del día"],
    digest_daily_review: ["Resumen del día", "Resumen del día"],
    digest_weekly_preview: ["Avance de la semana", "Avance de la semana"],
    digest_weekly_review: ["Resumen de la semana", "Resumen de la semana"],
  }),
  fr: moduleLabels({
    messages: ["Message", "Messages"],
    messages_follow_up: ["Message plus tard", "Plus tard"],
    reviews: ["Avis", "Avis"],
    changelog: ["Journal", "Journal"],
    reservations_pending: ["Réservation non confirmée", "Non confirmées"],
    reservations_change_request: ["Demande de modification", "Demandes de modification"],
    reservations_cancellation: ["Annulation", "Annulations"],
    reservations_activity: ["Activité des réservations", "Activité des réservations"],
    events_inquiry: ["Demande d’événement", "Demandes d’événement"],
    staff_shift_start: ["Début de service", "Début de service"],
    staff_shift_end: ["Fin de service", "Fin de service"],
    inventory_low_stock: ["Stock bas", "Stock bas"],
    inventory_po_delivery_due: ["Livraison à faire", "Livraisons à faire"],
    inventory_po_ordered: ["Commande passée", "Commandées"],
    inventory_po_closed: ["Commande clôturée", "Clôturées"],
    inventory_po_activity: ["Commande", "Commandes"],
    inventory_stock_activity: ["Stock", "Stock"],
    accounting_quotation: ["Devis", "Devis"],
    accounting_invoice: ["Facture", "Factures"],
    accounting_voucher: ["Justificatif", "Justificatifs"],
    staff_todo_completed: ["Tâche faite", "Tâches faites"],
    staff_todo_deferred: ["Tâche reportée", "Tâches reportées"],
    personal_reminder: ["Rappel personnel", "Rappels"],
    staff_messages: ["Message d’équipe", "Messages d’équipe"],
    staff_contract_signed: ["Contrat", "Contrats"],
    staff_document_assigned: ["Document", "Documents"],
    staff_display_time_request: ["Ajouter un horaire", "Ajouter un horaire"],
    staff_invite_accepted: ["Invitation acceptée", "Invitations acceptées"],
    staff_invite_declined: ["Invitation refusée", "Invitations refusées"],
    staff_display_clock_in: ["Prise de service écran", "Prise de service écran"],
    staff_display_clock_out: ["Fin de service écran", "Fin de service écran"],
    staff_display_break_start: ["Pause commencée", "Pause commencée"],
    staff_display_break_end: ["Pause terminée", "Pause terminée"],
    staff_permissions_granted: ["Nouveaux droits", "Nouveaux droits"],
    digest_daily_preview: ["Aperçu du jour", "Aperçu du jour"],
    digest_daily_review: ["Bilan du jour", "Bilan du jour"],
    digest_weekly_preview: ["Aperçu de la semaine", "Aperçu de la semaine"],
    digest_weekly_review: ["Bilan de la semaine", "Bilan de la semaine"],
  }),
  it: moduleLabels({
    messages: ["Messaggio", "Messaggi"],
    messages_follow_up: ["Messaggio più tardi", "Più tardi"],
    reviews: ["Recensione", "Recensioni"],
    changelog: ["Registro", "Registro"],
    reservations_pending: ["Prenotazione non confermata", "Non confermate"],
    reservations_change_request: ["Richiesta di modifica", "Richieste di modifica"],
    reservations_cancellation: ["Annullamento", "Annullamenti"],
    reservations_activity: ["Attività prenotazioni", "Attività prenotazioni"],
    events_inquiry: ["Richiesta evento", "Richieste evento"],
    staff_shift_start: ["Inizio turno", "Inizio turno"],
    staff_shift_end: ["Fine turno", "Fine turno"],
    inventory_low_stock: ["Scorte basse", "Scorte basse"],
    inventory_po_delivery_due: ["Consegna in scadenza", "Consegne in scadenza"],
    inventory_po_ordered: ["Ordine inviato", "Ordinati"],
    inventory_po_closed: ["Ordine chiuso", "Chiusi"],
    inventory_po_activity: ["Ordine", "Ordini"],
    inventory_stock_activity: ["Scorte", "Scorte"],
    accounting_quotation: ["Preventivo", "Preventivi"],
    accounting_invoice: ["Fattura", "Fatture"],
    accounting_voucher: ["Giustificativo", "Giustificativi"],
    staff_todo_completed: ["Attività completata", "Attività completate"],
    staff_todo_deferred: ["Attività rinviata", "Attività rinviate"],
    personal_reminder: ["Promemoria personale", "Promemoria"],
    staff_messages: ["Messaggio del team", "Messaggi del team"],
    staff_contract_signed: ["Contratto", "Contratti"],
    staff_document_assigned: ["Documento", "Documenti"],
    staff_display_time_request: ["Aggiungi orario", "Aggiungi orario"],
    staff_invite_accepted: ["Invito accettato", "Inviti accettati"],
    staff_invite_declined: ["Invito rifiutato", "Inviti rifiutati"],
    staff_display_clock_in: ["Ingresso display", "Ingresso display"],
    staff_display_clock_out: ["Uscita display", "Uscita display"],
    staff_display_break_start: ["Pausa iniziata", "Pausa iniziata"],
    staff_display_break_end: ["Pausa terminata", "Pausa terminata"],
    staff_permissions_granted: ["Nuovi permessi", "Nuovi permessi"],
    digest_daily_preview: ["Anteprima del giorno", "Anteprima del giorno"],
    digest_daily_review: ["Riepilogo del giorno", "Riepilogo del giorno"],
    digest_weekly_preview: ["Anteprima della settimana", "Anteprima della settimana"],
    digest_weekly_review: ["Riepilogo della settimana", "Riepilogo della settimana"],
  }),
  tr: moduleLabels({
    messages: ["Mesaj", "Mesajlar"],
    messages_follow_up: ["Mesaj sonra", "Sonra"],
    reviews: ["Değerlendirme", "Değerlendirmeler"],
    changelog: ["Günlük", "Günlük"],
    reservations_pending: ["Onaysız rezervasyon", "Onaysız"],
    reservations_change_request: ["Değişiklik isteği", "Değişiklik istekleri"],
    reservations_cancellation: ["İptal", "İptaller"],
    reservations_activity: ["Rezervasyon hareketi", "Rezervasyon hareketi"],
    events_inquiry: ["Etkinlik talebi", "Etkinlik talepleri"],
    staff_shift_start: ["Vardiya başlangıcı", "Vardiya başlangıcı"],
    staff_shift_end: ["Vardiya bitişi", "Vardiya bitişi"],
    inventory_low_stock: ["Düşük stok", "Düşük stok"],
    inventory_po_delivery_due: ["Teslimat zamanı", "Teslimatlar"],
    inventory_po_ordered: ["Sipariş verildi", "Sipariş edildi"],
    inventory_po_closed: ["Sipariş kapandı", "Kapandı"],
    inventory_po_activity: ["Sipariş", "Siparişler"],
    inventory_stock_activity: ["Stok", "Stok"],
    accounting_quotation: ["Teklif", "Teklifler"],
    accounting_invoice: ["Fatura", "Faturalar"],
    accounting_voucher: ["Belge", "Belgeler"],
    staff_todo_completed: ["Görev bitti", "Görevler bitti"],
    staff_todo_deferred: ["Görev ertelendi", "Görevler ertelendi"],
    personal_reminder: ["Kişisel hatırlatma", "Hatırlatmalar"],
    staff_messages: ["Ekip mesajı", "Ekip mesajları"],
    staff_contract_signed: ["Sözleşme", "Sözleşmeler"],
    staff_document_assigned: ["Belge", "Belgeler"],
    staff_display_time_request: ["Süre ekle", "Süre ekle"],
    staff_invite_accepted: ["Davet kabul edildi", "Davetler kabul edildi"],
    staff_invite_declined: ["Davet reddedildi", "Davetler reddedildi"],
    staff_display_clock_in: ["Ekran giriş", "Ekran giriş"],
    staff_display_clock_out: ["Ekran çıkış", "Ekran çıkış"],
    staff_display_break_start: ["Mola başladı", "Mola başladı"],
    staff_display_break_end: ["Mola bitti", "Mola bitti"],
    staff_permissions_granted: ["Yeni yetkiler", "Yeni yetkiler"],
    digest_daily_preview: ["Gün önizlemesi", "Gün önizlemesi"],
    digest_daily_review: ["Gün özeti", "Gün özeti"],
    digest_weekly_preview: ["Hafta önizlemesi", "Hafta önizlemesi"],
    digest_weekly_review: ["Hafta özeti", "Hafta özeti"],
  }),
  ar: moduleLabels({
    messages: ["رسالة", "رسائل"],
    messages_follow_up: ["رسالة لاحقاً", "لاحقاً"],
    reviews: ["تقييم", "تقييمات"],
    changelog: ["السجل", "السجل"],
    reservations_pending: ["حجز غير مؤكد", "غير مؤكدة"],
    reservations_change_request: ["طلب تعديل", "طلبات تعديل"],
    reservations_cancellation: ["إلغاء", "إلغاءات"],
    reservations_activity: ["نشاط الحجوزات", "نشاط الحجوزات"],
    events_inquiry: ["طلب مناسبة", "طلبات مناسبات"],
    staff_shift_start: ["بداية الوردية", "بداية الوردية"],
    staff_shift_end: ["نهاية الوردية", "نهاية الوردية"],
    inventory_low_stock: ["مخزون منخفض", "مخزون منخفض"],
    inventory_po_delivery_due: ["تسليم مستحق", "تسليمات مستحقة"],
    inventory_po_ordered: ["تم الطلب", "تم الطلب"],
    inventory_po_closed: ["أُغلق الطلب", "مغلقة"],
    inventory_po_activity: ["طلب", "طلبات"],
    inventory_stock_activity: ["المخزون", "المخزون"],
    accounting_quotation: ["عرض", "عروض"],
    accounting_invoice: ["فاتورة", "فواتير"],
    accounting_voucher: ["مستند", "مستندات"],
    staff_todo_completed: ["مهمة منجزة", "مهام منجزة"],
    staff_todo_deferred: ["مهمة مؤجلة", "مهام مؤجلة"],
    personal_reminder: ["تذكير شخصي", "تذكيرات"],
    staff_messages: ["رسالة الفريق", "رسائل الفريق"],
    staff_contract_signed: ["عقد", "عقود"],
    staff_document_assigned: ["مستند", "مستندات"],
    staff_display_time_request: ["إضافة وقت", "إضافة وقت"],
    staff_invite_accepted: ["دعوة مقبولة", "دعوات مقبولة"],
    staff_invite_declined: ["دعوة مرفوضة", "دعوات مرفوضة"],
    staff_display_clock_in: ["دخول الشاشة", "دخول الشاشة"],
    staff_display_clock_out: ["خروج الشاشة", "خروج الشاشة"],
    staff_display_break_start: ["بدأت الاستراحة", "بدأت الاستراحة"],
    staff_display_break_end: ["انتهت الاستراحة", "انتهت الاستراحة"],
    staff_permissions_granted: ["صلاحيات جديدة", "صلاحيات جديدة"],
    digest_daily_preview: ["لمحة اليوم", "لمحة اليوم"],
    digest_daily_review: ["خلاصة اليوم", "خلاصة اليوم"],
    digest_weekly_preview: ["لمحة الأسبوع", "لمحة الأسبوع"],
    digest_weekly_review: ["خلاصة الأسبوع", "خلاصة الأسبوع"],
  }),
  zh: moduleLabels({
    messages: ["消息", "消息"],
    messages_follow_up: ["稍后消息", "稍后"],
    reviews: ["评价", "评价"],
    changelog: ["更新日志", "更新日志"],
    reservations_pending: ["未确认预订", "未确认"],
    reservations_change_request: ["变更请求", "变更请求"],
    reservations_cancellation: ["取消", "取消"],
    reservations_activity: ["预订动态", "预订动态"],
    events_inquiry: ["活动咨询", "活动咨询"],
    staff_shift_start: ["班次开始", "班次开始"],
    staff_shift_end: ["班次结束", "班次结束"],
    inventory_low_stock: ["库存偏低", "库存偏低"],
    inventory_po_delivery_due: ["到货到期", "到货到期"],
    inventory_po_ordered: ["订单已下", "已下单"],
    inventory_po_closed: ["订单已完成", "已完成"],
    inventory_po_activity: ["订单", "订单"],
    inventory_stock_activity: ["库存", "库存"],
    accounting_quotation: ["报价", "报价"],
    accounting_invoice: ["发票", "发票"],
    accounting_voucher: ["凭证", "凭证"],
    staff_todo_completed: ["待办已完成", "待办已完成"],
    staff_todo_deferred: ["待办已推迟", "待办已推迟"],
    personal_reminder: ["个人提醒", "提醒"],
    staff_messages: ["团队消息", "团队消息"],
    staff_contract_signed: ["合同", "合同"],
    staff_document_assigned: ["文档", "文档"],
    staff_display_time_request: ["补记时间", "补记时间"],
    staff_invite_accepted: ["已接受邀请", "已接受邀请"],
    staff_invite_declined: ["已拒绝邀请", "已拒绝邀请"],
    staff_display_clock_in: ["显示屏签到", "显示屏签到"],
    staff_display_clock_out: ["显示屏签退", "显示屏签退"],
    staff_display_break_start: ["休息已开始", "休息已开始"],
    staff_display_break_end: ["休息已结束", "休息已结束"],
    staff_permissions_granted: ["新权限", "新权限"],
    digest_daily_preview: ["每日预览", "每日预览"],
    digest_daily_review: ["每日回顾", "每日回顾"],
    digest_weekly_preview: ["每周预览", "每周预览"],
    digest_weekly_review: ["每周回顾", "每周回顾"],
  }),
};

function moduleLabels(
  rows: Record<NotificationModuleId, [string, string]>,
): Record<NotificationModuleId, ModuleNoticeLabel> {
  const out = {} as Record<NotificationModuleId, ModuleNoticeLabel>;
  for (const [id, pair] of Object.entries(rows) as Array<
    [NotificationModuleId, [string, string]]
  >) {
    out[id] = { one: pair[0], many: pair[1] };
  }
  return out;
}

export type StaffNotificationCopy = Phrase & {
  fillName: (template: string, name: string) => string;
};

export function staffNotificationCopy(
  locale: string | null | undefined,
): StaffNotificationCopy {
  const phrase = PHRASES[normalizeAppLocale(locale)];
  return {
    ...phrase,
    fillName: (template, name) => template.replaceAll("{name}", name),
  };
}

export function moduleNoticeLabel(
  moduleId: NotificationModuleId,
  locale: string | null | undefined,
  form: "one" | "many" = "one",
): string {
  const row = MODULES[normalizeAppLocale(locale)][moduleId];
  return form === "many" ? row.many : row.one;
}
