/** Module, die im Dashboard-„Heute live“-Feed erscheinen (notification_events). */
export const LIVE_ACTIVITY_FEED_MODULES = [
  "staff_display_clock_in",
  "staff_display_clock_out",
  "staff_shift_start",
  "staff_shift_end",
  "reservations_pending",
  "reservations_change_request",
  "reservations_cancellation",
  "events_inquiry",
  "messages",
  "reviews",
  "inventory_low_stock",
  "inventory_po_delivery_due",
  "inventory_po_activity",
  "inventory_stock_activity",
  "accounting_quotation",
  "accounting_invoice",
  "accounting_voucher",
  "staff_todo_completed",
  "staff_todo_deferred",
  "personal_reminder",
  "staff_messages",
  "staff_contract_signed",
  "staff_document_assigned",
  "staff_display_time_request",
  "staff_invite_accepted",
  "staff_invite_declined",
  "staff_permissions_granted",
] as const;
