/** Restaurant-App unter `/dashboard/*` (nicht Superadmin, nicht öffentliches Profil). */

export const DASHBOARD_HOME = "/dashboard";

export const APP_ROUTES = {
  dashboard: DASHBOARD_HOME,
  menu: {
    root: "/dashboard/menu",
    overview: "/dashboard/menu/overview",
    statistics: "/dashboard/menu/statistics",
    export: "/dashboard/menu/export",
    embed: "/dashboard/menu/embed",
  },
  inventory: {
    root: "/dashboard/inventory",
    overview: "/dashboard/inventory/overview",
    order: "/dashboard/inventory/purchase-orders",
    statistics: "/dashboard/inventory/statistics",
  },
  reservierungen: {
    root: "/dashboard/reservations",
    overview: "/dashboard/reservations/overview",
    floorPlan: "/dashboard/reservations/floor-plan",
    stats: "/dashboard/reservations/statistics",
    settings: "/dashboard/reservations/settings",
    embed: "/dashboard/reservations/embed",
    protokoll: "/dashboard/reservations/log",
  },
  pos: {
    root: "/dashboard/pos",
    overview: "/dashboard/pos/overview",
    orders: "/dashboard/pos/orders",
    receipts: "/dashboard/pos/receipts",
    giftVouchers: "/dashboard/pos/gift-vouchers",
    statistics: "/dashboard/pos/statistics",
    reports: "/dashboard/pos/reports",
    settings: "/dashboard/pos/settings",
    settingsFiscalPayment: "/dashboard/pos/settings/fiscal-payment",
    settingsPrintersRouting: "/dashboard/pos/settings/printer-routing",
    settingsKitchen: "/dashboard/pos/settings/kitchen",
    settingsInventoryVoid: "/dashboard/pos/settings/inventory-void",
    settingsGiftVouchers: "/dashboard/pos/settings/gift-vouchers",
    settingsDevicesRights: "/dashboard/pos/settings/device-permissions",
    settingsDevices: "/dashboard/pos/settings/devices",
  },
  kontakte: {
    root: "/dashboard/contacts",
    messages: "/dashboard/contacts/messages",
    /** Standard-Posteingang: Chip „Alle“, nicht letzter Kanal-Filter (Keep-alive). */
    messagesInbox: "/dashboard/contacts/messages?platform=all",
    overview: "/dashboard/contacts/overview",
    statistics: "/dashboard/contacts/statistics",
    export: "/dashboard/contacts/export",
    settings: "/dashboard/contacts/settings",
  },
  bewertungen: {
    root: "/dashboard/reviews",
    overview: "/dashboard/reviews/overview",
    statistics: "/dashboard/reviews/statistics",
    embed: "/dashboard/reviews/embed",
    settings: "/dashboard/reviews/settings",
  },
  insights: {
    root: "/dashboard/insights",
    overview: "/dashboard/insights/overview",
  },
  dokumente: {
    root: "/dashboard/documents",
    overview: "/dashboard/documents/overview",
    statistics: "/dashboard/documents/statistics",
    log: "/dashboard/documents/log",
  },
  checklisten: {
    root: "/dashboard/tasks",
    meine: "/dashboard/tasks/mine",
    nachrichten: "/dashboard/tasks/messages",
    todos: "/dashboard/tasks",
    vorlagen: "/dashboard/tasks/templates",
    geraete: "/dashboard/tasks/devices",
    eintraege: "/dashboard/tasks/entries",
    protokoll: "/dashboard/tasks/log",
    settings: "/dashboard/tasks/settings",
  },

  mitarbeiter: {
    root: "/dashboard/staff",
    overview: "/dashboard/staff/overview",
    schedule: "/dashboard/staff/shift-plan",
    contracts: "/dashboard/staff/contracts",
    documents: "/dashboard/staff/documents",
    hours: "/dashboard/staff/work-hours",
    hoursFix: "/dashboard/staff/work-hours/fix",
    hoursPayroll: "/dashboard/staff/work-hours/payroll",
    statistics: "/dashboard/staff/statistics",
    export: "/dashboard/staff/export",
    todos: "/dashboard/tasks",
  },
  buchfuehrung: {
    root: "/dashboard/accounting",
    invoices: "/dashboard/accounting/invoices",
    quotations: "/dashboard/accounting/quotations",
    vouchers: "/dashboard/accounting/vouchers",
    cashBook: "/dashboard/accounting/cash-book",
    statistics: "/dashboard/accounting/statistics",
    settings: "/dashboard/accounting/settings",
  },
  galerie: {
    root: "/dashboard/gallery",
    overview: "/dashboard/gallery/overview",
    statistics: "/dashboard/gallery/statistics",
    embed: "/dashboard/gallery/embed",
    settings: "/dashboard/gallery/settings",
  },
  events: {
    root: "/dashboard/events",
    overview: "/dashboard/events/overview",
    embed: "/dashboard/events/embed",
    statistics: "/dashboard/events/statistics",
    settings: "/dashboard/events/settings",
  },
  news: {
    root: "/dashboard/news",
    overview: "/dashboard/news/overview",
    autopilot: "/dashboard/news/autopilot",
    statistics: "/dashboard/news/statistics",
    embed: "/dashboard/news/embed",
    settings: "/dashboard/news/settings",
  },
  settings: {
    /** Prefix for `startsWith` (sidebar active) — not a SPA leaf route. */
    root: "/dashboard/settings",
    /** Chrome gear / sidebar — always a registered SPA page (not redirect-only `/settings`). */
    entry: "/dashboard/settings/restaurant",
    restaurant: "/dashboard/settings/restaurant",
    dashboard: "/dashboard/settings/dashboard",
    team: "/dashboard/settings/team",
    openingHours: "/dashboard/settings/opening-hours",
    openingHoursEmbed: "/dashboard/settings/opening-hours/embed",
    integrations: "/dashboard/settings/integrations",
    displays: "/dashboard/settings/displays",
    api: "/dashboard/settings/api",
    billing: "/dashboard/settings/billing",
  },
  profile: {
    root: "/dashboard/profile",
    personal: "/dashboard/profile/personal",
    login: "/dashboard/profile/sign-in",
    notifications: "/dashboard/profile/notifications",
    workHours: "/dashboard/profile/work-hours",
    schedule: "/dashboard/profile/schedule",
    availability: "/dashboard/profile/availability",
    documents: "/dashboard/profile/documents",
    displayPin: "/dashboard/profile/display-pin",
  },
  /** Kunden-Changelog (Dashboard-SPA-Tab-Stack, Soft-Nav). */
  changelog: "/dashboard/changelog",
} as const;

export { LEGACY_MODULE_REDIRECTS } from "./english-app-paths";
