function normalizePath(p: string): string {
  if (p.length > 1 && p.endsWith("/")) return p.slice(0, -1);
  return p;
}

/** Bekannte Routen → lesbarer Abschnitt (pro Pfad-Präfix). */
const PATH_PAGE_TITLES: Record<string, string> = {
  "/": "Startseite",
  "/login": "Login",
  "/docs": "Docs",
  "/imprint": "Impressum",
  "/privacy": "Datenschutz",
  "/terms": "AGB",
  "/dpa": "AVV",
  "/data-deletion": "Datenlöschung",
  "/dashboard": "Dashboard",
  "/dashboard/menu": "Speisekarte",
  "/dashboard/menu/overview": "Speisekarte",
  "/dashboard/menu/statistics": "Statistiken",
  "/dashboard/menu/export": "Export",
  "/dashboard/menu/embed": "Einbinden",
  "/dashboard/reviews": "Bewertungen",
  "/dashboard/reviews/overview": "Übersicht",
  "/dashboard/reviews/statistics": "Statistiken",
  "/dashboard/reviews/embed": "Einbinden",
  "/dashboard/reviews/settings": "Einstellungen",
  "/dashboard/news": "News",
  "/dashboard/news/overview": "Übersicht",
  "/dashboard/news/autopilot": "Autopilot",
  "/dashboard/news/statistics": "Statistiken",
  "/dashboard/news/embed": "Einbinden",
  "/dashboard/news/settings": "Einstellungen",
  "/dashboard/inventory": "Bestand",
  "/dashboard/inventory/overview": "Bestand",
  "/dashboard/inventory/purchase-orders": "Bestellung",
  "/dashboard/inventory/statistics": "Statistiken",
  "/dashboard/contacts": "Nachrichten",
  "/dashboard/contacts/messages": "Nachrichten",
  "/dashboard/contacts/overview": "Kontakte",
  "/dashboard/contacts/statistics": "Statistiken",
  "/dashboard/contacts/export": "Export",
  "/dashboard/contacts/settings": "Einstellungen",
  "/dashboard/documents": "Dokumente",
  "/dashboard/documents/overview": "Übersicht",
  "/dashboard/documents/statistics": "Statistiken",
  "/dashboard/documents/log": "Protokoll",
  "/dashboard/staff": "Mitarbeiter",
  "/dashboard/staff/overview": "Übersicht",
  "/dashboard/staff/shift-plan": "Schichtplan",
  "/dashboard/staff/contracts": "Verträge",
  "/dashboard/staff/work-hours": "Arbeitszeiten",
  "/dashboard/staff/work-hours/fix": "Arbeitszeiten · Beheben",
  "/dashboard/staff/work-hours/payroll": "Arbeitszeiten · Abrechnung",
  "/dashboard/staff/statistics": "Statistiken",
  "/dashboard/staff/export": "Export",
  "/dashboard/accounting": "Buchführung",
  "/dashboard/accounting/invoices": "Rechnungen",
  "/dashboard/accounting/quotations": "Angebote",
  "/dashboard/accounting/vouchers": "Belege",
  "/dashboard/accounting/cash-book": "Kasse",
  "/dashboard/accounting/statistics": "Statistiken",
  "/dashboard/accounting/settings": "Einstellungen",
  "/dashboard/gallery": "Galerie",
  "/dashboard/gallery/overview": "Übersicht",
  "/dashboard/gallery/statistics": "Statistiken",
  "/dashboard/gallery/embed": "Einbinden",
  "/dashboard/gallery/settings": "Einstellungen",
  "/dashboard/reservations": "Reservierungen",
  "/dashboard/reservations/overview": "Übersicht",
  "/dashboard/reservations/floor-plan": "Tischplan",
  "/dashboard/reservations/statistics": "Statistiken",
  "/dashboard/reservations/settings": "Einstellungen",
  "/dashboard/reservations/embed": "Einbinden",
  "/dashboard/reservations/log": "Protokoll",
  "/dashboard/pos": "POS",
  "/dashboard/pos/overview": "Übersicht",
  "/dashboard/pos/orders": "Bestellungen",
  "/dashboard/pos/receipts": "Quittungen",
  "/dashboard/pos/gift-vouchers": "Gutscheine",
  "/dashboard/pos/statistics": "Statistiken",
  "/dashboard/pos/reports": "Berichte",
  "/dashboard/pos/settings": "Einstellungen",
  "/dashboard/pos/settings/fiscal-payment": "Fiskal & Zahlung",
  "/dashboard/pos/settings/printer-routing": "Drucker & Routing",
  "/dashboard/pos/settings/kitchen": "Küche",
  "/dashboard/pos/settings/inventory-void": "Bestand & Storno",
  "/dashboard/pos/settings/gift-vouchers": "Gutscheine",
  "/dashboard/pos/settings/devices": "Geräte",
  "/dashboard/events": "Events",
  "/dashboard/events/overview": "Übersicht",
  "/dashboard/events/embed": "Einbinden",
  "/dashboard/events/statistics": "Statistiken",
  "/dashboard/events/settings": "Einstellungen",
  "/dashboard/settings": "Einstellungen",
  "/dashboard/settings/restaurant": "Übersicht",
  "/dashboard/settings/team": "Team",
  "/dashboard/settings/opening-hours": "Öffnungszeiten",
  "/dashboard/settings/dashboard": "Dashboard",
  "/dashboard/settings/integrations": "Integrationen",
  "/dashboard/settings/displays": "Displays",
  "/dashboard/settings/api": "API",
  "/dashboard/settings/billing": "Abo",
  "/dashboard/profile": "Profil",
  "/dashboard/profile/personal": "Übersicht",
  "/dashboard/profile/sign-in": "Anmeldung",
  "/dashboard/profile/work-hours": "Meine Arbeitszeiten",
  "/dashboard/profile/schedule": "Dienstplan",
  "/dashboard/profile/documents": "Meine Dokumente",
  "/dashboard/profile/notifications": "Benachrichtigungen",
  "/dashboard/profile/availability": "Verfügbarkeit",
  "/dashboard/profile/display-pin": "Display-PIN",
  "/dashboard/pos/settings/device-permissions": "Geräte-Rechte",
  "/settings": "Einstellungen",
  "/settings/restaurant": "Übersicht",
  "/settings/team": "Team",
  "/settings/opening-hours": "Öffnungszeiten",
  "/settings/dashboard": "Dashboard",
  "/settings/integrations": "Integrationen",
  "/settings/displays": "Displays",
  "/settings/api": "API",
  "/dashboard/tasks": "Aufgaben",
  "/dashboard/tasks/mine": "Meine",
  "/dashboard/tasks/messages": "Nachrichten",
  "/dashboard/tasks/todos": "Aufgaben",

  "/dashboard/tasks/templates": "Aufgaben",
  "/settings/eigenkontrolle/templates": "Aufgaben",
  "/dashboard/tasks/devices": "Aufgaben",
  "/dashboard/tasks/entries": "Protokoll",
  "/dashboard/tasks/log": "Protokoll",
  "/dashboard/tasks/settings": "Einstellungen",
  "/settings/eigenkontrolle": "Aufgaben",
  "/settings/eigenkontrolle/devices": "Aufgaben",
  "/settings/eigenkontrolle/entries": "Protokoll",
  "/settings/eigenkontrolle/log": "Protokoll",
  "/settings/eigenkontrolle/settings": "Einstellungen",
  "/profile": "Profil",
  "/profile/personal": "Übersicht",
  "/profile/sign-in": "Anmeldung",
  "/profile/arbeitszeiten": "Meine Arbeitszeiten",
  "/profile/dienstplan": "Dienstplan",
  "/profile/dokumente": "Meine Dokumente",
  "/workspace": "Workspace",
  "/workspace/restaurants": "Restaurants",
  "/workspace/team": "Team",
  "/changelog": "Changelog",
  "/dashboard/changelog": "Changelog",
  "/superadmin": "Superadmin",
  "/superadmin/general": "Allgemein",
  "/superadmin/users": "User",
  "/superadmin/users/export": "Export",
  "/superadmin/users/statistics": "Statistiken",
  "/superadmin/restaurants": "Restaurants",
  "/superadmin/restaurants/export": "Export",
  "/superadmin/restaurants/statistics": "Statistiken",
  "/superadmin/subscriptions": "Abonnements",
  "/superadmin/subscriptions/payments": "Zahlungen",
  "/superadmin/subscriptions/statistics": "Statistiken",
  "/superadmin/integrations": "Integrationen",
  "/superadmin/waha": "WAHA",
  "/superadmin/ops": "Ops",
  "/superadmin/analytics": "Statistik",
  "/superadmin/analytics/usage": "Nutzung",
  "/superadmin/database": "Live & VPS",
  "/superadmin/load-strategy": "Lade-Strategie",
  "/superadmin/newsletter": "Newsletter",
  "/superadmin/newsletter/templates": "Vorlagen",
  "/newsletter/subscribe": "Newsletter anmelden",
  "/newsletter/unsubscribe": "Newsletter abmelden",
  "/superadmin/changelog": "Changelog",
  "/superadmin/notifications": "Benachrichtigungen",
  "/superadmin/templates": "Vorlagen",
  "/superadmin/templates/contract-templates": "Vertragsvorlagen",
  "/superadmin/contract-templates": "Vertragsvorlagen",
};

const SEGMENT_SLUG_LABELS: Record<string, string> = {
  superadmin: "Superadmin",
  allgemein: "Allgemein",
  reservierungen: "Reservierungen",
  einstellungen: "Einstellungen",
  uebersicht: "Übersicht",
  tischplan: "Tischplan",
  statistiken: "Statistiken",
  einbinden: "Einbinden",
  mitarbeiter: "Mitarbeiter",
  schichtplan: "Schichtplan",
  vertraege: "Verträge",
  arbeitszeiten: "Arbeitszeiten",
  dienstplan: "Dienstplan",
  dokumente: "Dokumente",
  protokoll: "Protokoll",
  kontakte: "Nachrichten",
  nachrichten: "Nachrichten",
  inventory: "Bestand",
  bestellung: "Bestellung",
  integrationen: "Integrationen",
  datenbank: "Datenbank",
  restaurants: "Restaurants",
  users: "User",
  dashboard: "Dashboard",
  settings: "Einstellungen",
  branding: "Branding",
  displays: "Displays",
  profile: "Profil",
  workspace: "Workspace",
  changelog: "Changelog",
  menu: "Speisekarte",
  export: "Export",
  login: "Login",
  impressum: "Impressum",
  datenschutz: "Datenschutz",
  agb: "AGB",
  avv: "AVV",
  datenloeschung: "Datenlöschung",
  docs: "Docs",
  reservations: "Reservierungen",
  contacts: "Nachrichten",
  reviews: "Bewertungen",
  documents: "Dokumente",
  tasks: "Aufgaben",
  staff: "Mitarbeiter",
  accounting: "Buchführung",
  gallery: "Galerie",
  overview: "Übersicht",
  statistics: "Statistiken",
  embed: "Einbinden",
  log: "Protokoll",
  messages: "Nachrichten",
  "purchase-orders": "Bestellung",
  orders: "Bestellungen",
  "floor-plan": "Tischplan",
  "shift-plan": "Schichtplan",
  contracts: "Verträge",
  "work-hours": "Arbeitszeiten",
  invoices: "Rechnungen",
  quotations: "Angebote",
  vouchers: "Belege",
  "cash-book": "Kasse",
  receipts: "Quittungen",
  "gift-vouchers": "Gutscheine",
  reports: "Berichte",
  mine: "Meine",
  templates: "Vorlagen",
  devices: "Geräte",
  entries: "Einträge",
  fix: "Beheben",
  payroll: "Abrechnung",
  "opening-hours": "Öffnungszeiten",
  integrations: "Integrationen",
  billing: "Abo",
  personal: "Übersicht",
  "sign-in": "Anmeldung",
  notifications: "Benachrichtigungen",
  schedule: "Dienstplan",
  availability: "Verfügbarkeit",
  "fiscal-payment": "Fiskal & Zahlung",
  "printer-routing": "Drucker & Routing",
  kitchen: "Küche",
  "inventory-void": "Bestand & Storno",
  "device-permissions": "Geräte-Rechte",
  "display-pin": "Display-PIN",
  general: "Allgemein",
  analytics: "Statistik",
  usage: "Nutzung",
  subscriptions: "Abonnements",
  waitlist: "Warteliste",
  database: "Datenbank",
  "load-strategy": "Lade-Strategie",
  "contract-templates": "Vertragsvorlagen",
  payments: "Zahlungen",
  imprint: "Impressum",
  privacy: "Datenschutz",
  "data-deletion": "Datenlöschung",
  terms: "AGB",
  dpa: "AVV",
  "new-password": "Neues Passwort",
  invitation: "Einladung",
  review: "Bewertung",
  subscribe: "Anmelden",
  unsubscribe: "Abmelden",
  handbook: "Handbuch",
  "getting-started": "Erste Schritte",
  "public-profile": "Öffentliches Profil",
  contact: "Kontakt",
  reserve: "Reservieren",
  "event-inquiry": "Veranstaltung",
};

function humanizePathSegment(slug: string): string {
  const key = slug.toLowerCase();
  if (SEGMENT_SLUG_LABELS[key]) return SEGMENT_SLUG_LABELS[key];
  if (PATH_PAGE_TITLES[`/${key}`]) return PATH_PAGE_TITLES[`/${key}`]!;
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

/**
 * Tab-Inhalt aus URL-Pfad: jedes Segment nach `/` wird lesbar — z. B.
 * `/superadmin/general` → `Superadmin - Allgemein` (stabil, unabhängig vom Modul-Chrome).
 */
export function resolveDocumentPageTitle(pathname: string): string {
  const path = normalizePath(pathname);
  if (path === "/") return "Startseite";

  const segments = path.split("/").filter(Boolean);
  const parts: string[] = [];

  for (let i = 0; i < segments.length; i++) {
    const prefix = `/${segments.slice(0, i + 1).join("/")}`;
    const label = PATH_PAGE_TITLES[prefix] ?? humanizePathSegment(segments[i]!);
    if (parts.length === 0 || parts[parts.length - 1] !== label) {
      parts.push(label);
    }
  }

  return parts.join(" - ");
}
