#!/usr/bin/env node
/**
 * Schreibt apps/staff/.env für physisches iPhone / TestFlight LAN-Build:
 * Supabase-Keys aus `supabase status`, Host = Mac-LAN-IP (nicht 127.0.0.1).
 *
 * Voraussetzung: pnpm db:start
 * Danach: node apps/staff/scripts/generate-staff-env.js
 */
import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const STAFF_ENV = resolve(ROOT, "apps/staff/.env");

function parseStatusEnv(raw) {
  const out = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function detectLanIp() {
  const iface = process.env.GWADA_LAN_INTERFACE ?? "en0";
  try {
    const ip = execSync(`ipconfig getifaddr ${iface}`, {
      encoding: "utf8",
    }).trim();
    if (ip) return ip;
  } catch {
    // try en1 (Ethernet / alternate Wi‑Fi)
  }
  if (iface !== "en1") {
    try {
      const ip = execSync("ipconfig getifaddr en1", { encoding: "utf8" }).trim();
      if (ip) return ip;
    } catch {
      // fall through
    }
  }
  console.error(
    "Fehler: Keine LAN-IP gefunden (ipconfig getifaddr en0/en1).",
  );
  console.error("Optional: GWADA_LAN_INTERFACE=… setzen oder GWADA_LAN_IP=192.168.x.x");
  process.exit(1);
}

function readExistingEnv(path) {
  if (!existsSync(path)) return {};
  const out = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function main() {
  let statusRaw = "";
  try {
    statusRaw = execSync("npx supabase status -o env", {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (err) {
    console.error(
      "Fehler: `supabase status` — läuft die lokale DB? (pnpm db:start)",
    );
    process.exit(1);
  }

  const status = parseStatusEnv(statusRaw);
  const publishable = status.PUBLISHABLE_KEY ?? status.ANON_KEY;
  if (!publishable) {
    console.error("Fehler: PUBLISHABLE_KEY fehlt in supabase status.");
    process.exit(1);
  }

  const lanIp = process.env.GWADA_LAN_IP?.trim() || detectLanIp();
  const supabasePort = process.env.GWADA_SUPABASE_PORT ?? "54321";
  const webPort = process.env.GWADA_WEB_PORT ?? "3000";

  const existing = readExistingEnv(STAFF_ENV);
  const lines = [
    "# Auto-generated by scripts/staff-lan-env.mjs — nicht committen (in .gitignore ergänzen falls nötig)",
    `# LAN-IP: ${lanIp} — iPhone muss im gleichen WLAN sein`,
    "",
    `EXPO_PUBLIC_SUPABASE_URL=http://${lanIp}:${supabasePort}`,
    `EXPO_PUBLIC_SUPABASE_ANON_KEY=${publishable}`,
    `EXPO_PUBLIC_GWADA_API_URL=http://${lanIp}:${webPort}`,
    "",
  ];

  writeFileSync(STAFF_ENV, lines.join("\n"));

  console.log(`→ ${STAFF_ENV}`);
  console.log(`  EXPO_PUBLIC_SUPABASE_URL=http://${lanIp}:${supabasePort}`);
  console.log(`  EXPO_PUBLIC_GWADA_API_URL=http://${lanIp}:${webPort}`);
  console.log(`  EXPO_PUBLIC_SUPABASE_ANON_KEY=(publishable)`);
  console.log("");
  console.log("Als Nächstes:");
  console.log("  node apps/staff/scripts/generate-staff-env.js");
  console.log("  pnpm dev   # Web-API auf Port", webPort);
  console.log("");
  console.log(
    "Für EAS preview-lan: gleiche Werte per `pnpm staff:eas-env:preview-lan` setzen",
  );
}

main();
